import {
  BiomarkerItem,
  CellPoint,
  ClusterSummary,
  DatasetCohort,
  DotPlotItem,
  ExperimentMetadata,
  PathwayEnrichment,
  PipelineConfig,
  PipelineLogEntry,
  PipelineStepStatus,
  QCSummary,
  ScreePlotPoint,
  SingleCellDetail,
  TopologyBenchmark,
} from '../types';

// ============================================================================
// Multi-Dataset Cohorts Registry (Industry-Grade Multi-Study Repository)
// ============================================================================

export const DATASET_COHORTS: DatasetCohort[] = [
  {
    id: 'pbmc3k',
    name: '10x Human PBMC 3K Immune Profiling',
    shortLabel: 'PBMC Immune',
    organ: 'Peripheral Blood',
    disease: 'Healthy Donor Control',
    technology: '10x Chromium 3\' v3',
    cell_count: 4300,
    gene_count: 2050,
    median_umi: 4820,
    sparsity: 92.4,
    accession: '10X-PBMC-3K-V3',
    description: 'Gold-standard scRNA-seq benchmark profiling peripheral lymphocytes, monocytes, and dendritic lineages with robust ground truth.',
    colorBadge: 'var(--cyan-400)',
  },
  {
    id: 'gbm_tme',
    name: 'Glioblastoma Multiforme TME Atlas',
    shortLabel: 'GBM Tumor TME',
    organ: 'Neocortex / Brain',
    disease: 'IDH-wt Glioblastoma (Grade IV)',
    technology: 'Smart-seq2 Full-Length',
    cell_count: 3450,
    gene_count: 2420,
    median_umi: 8640,
    sparsity: 87.8,
    accession: 'GEO: GSE131928',
    description: 'Neoplastic stem-like glioma populations, tumor-associated macrophages (TAMs), infiltrating lymphocytes, and reactive astrocytes.',
    colorBadge: 'var(--purple-400)',
  },
  {
    id: 'pancreas_islets',
    name: 'Human Pancreatic Islets Endocrine Architecture',
    shortLabel: 'Pancreatic Islets',
    organ: 'Pancreas',
    disease: 'Type 2 Diabetes (T2D) vs Normoglycemic',
    technology: 'inDrop / Cel-Seq2',
    cell_count: 2850,
    gene_count: 1980,
    median_umi: 3950,
    sparsity: 93.7,
    accession: 'GEO: GSE84133',
    description: 'Single-cell dissection of pancreatic islet endocrine cells (alpha, beta, delta, gamma) and exocrine ductal/acinar architecture.',
    colorBadge: 'var(--emerald-400)',
  },
  {
    id: 'covid_balf',
    name: 'COVID-19 Bronchoalveolar Lavage Fluid (BALF)',
    shortLabel: 'COVID-19 Pulmonary',
    organ: 'Lung / Bronchoalveolar',
    disease: 'Severe COVID-19 ARDS',
    technology: '10x Chromium 5\' + V(D)J',
    cell_count: 3820,
    gene_count: 2240,
    median_umi: 5210,
    sparsity: 90.9,
    accession: 'GEO: GSE145926',
    description: 'Severe pulmonary hyper-inflammation with pathogenic macrophage expansion, exhausted CD8+ T cells, and interferon storm signatures.',
    colorBadge: 'var(--rose-400)',
  },
];

export const DEFAULT_PIPELINE_CONFIG: PipelineConfig = {
  qc_min_counts: 500,
  qc_min_genes: 200,
  qc_max_mito: 10.0,
  n_top_genes: 2000,
  n_pcs: 30,
  k_neighbors: 15,
  leiden_resolution: 0.5,
  umap_min_dist: 0.3,
  fdr_threshold: 0.05,
  de_method: 'wilcoxon',
};

// ============================================================================
// Cohort 1: PBMC 3K (Default)
// ============================================================================

export const INITIAL_EXPERIMENT: ExperimentMetadata = {
  id: 1,
  name: 'PBMC Immune Profiling & Biomarker Discovery',
  description: 'Single-cell transcriptome profiling of 4,300 peripheral blood mononuclear cells with hybrid topology preservation.',
  dataset_name: 'PBMC_5Populations_v1.h5ad',
  created_at: '2026-09-08 14:30:00 UTC',
  status: 'completed',
  cell_count: 4300,
  gene_count: 2050,
};

export const INITIAL_PIPELINE_STEPS: PipelineStepStatus[] = [
  { id: 1, step: 'qc', status: 'completed', progress: 100, completed_at: '14:31:10' },
  { id: 2, step: 'preprocess', status: 'completed', progress: 100, completed_at: '14:32:04' },
  { id: 3, step: 'pca', status: 'completed', progress: 100, completed_at: '14:32:45' },
  { id: 4, step: 'umap', status: 'completed', progress: 100, completed_at: '14:34:12' },
  { id: 5, step: 'cluster', status: 'completed', progress: 100, completed_at: '14:34:55' },
  { id: 6, step: 'de', status: 'completed', progress: 100, completed_at: '14:36:20' },
  { id: 7, step: 'biomarkers', status: 'completed', progress: 100, completed_at: '14:37:05' },
];

export const TOPOLOGY_BENCHMARKS: Record<string, TopologyBenchmark> = {
  hybrid: {
    method: 'Hybrid PCA → UMAP (CellMap)',
    knn_preservation: 0.884,
    trustworthiness: 0.942,
    continuity: 0.961,
    runtime_seconds: 4.82,
    visualization_latency_ms: 4820,
    global_distance_correlation: 0.748,
    dual_objective_score: 0.927,
  },
  direct: {
    method: 'Direct UMAP (Raw HVG)',
    knn_preservation: 0.695,
    trustworthiness: 0.867,
    continuity: 0.812,
    runtime_seconds: 14.35,
    visualization_latency_ms: 14350,
    global_distance_correlation: 0.381,
    dual_objective_score: 0.769,
  },
  pca: {
    method: 'Principal Component Analysis (PC1 vs PC2)',
    knn_preservation: 0.612,
    trustworthiness: 0.915,
    continuity: 0.894,
    runtime_seconds: 0.64,
    visualization_latency_ms: 640,
    global_distance_correlation: 0.821,
    dual_objective_score: 0.858,
  },
};

export const SCREE_PLOT_DATA: ScreePlotPoint[] = [
  { pc: 1, variance: 0.1842, cumulative: 0.1842 },
  { pc: 2, variance: 0.0921, cumulative: 0.2763 },
  { pc: 3, variance: 0.0714, cumulative: 0.3477 },
  { pc: 4, variance: 0.0582, cumulative: 0.4059 },
  { pc: 5, variance: 0.0471, cumulative: 0.4530 },
  { pc: 6, variance: 0.0389, cumulative: 0.4919 },
  { pc: 7, variance: 0.0312, cumulative: 0.5231 },
  { pc: 8, variance: 0.0278, cumulative: 0.5509 },
  { pc: 9, variance: 0.0241, cumulative: 0.5750 },
  { pc: 10, variance: 0.0215, cumulative: 0.5965 },
];

export const QC_METRICS: QCSummary = {
  cells_before: 4618,
  cells_after: 4300,
  genes_before: 2050,
  genes_after: 2000,
  median_counts: 4820,
  median_genes: 1240,
  median_mito_pct: 3.42,
  doublet_rate_pct: 3.8,
  low_quality_dropped: 218,
  apoptotic_dropped: 100,
};

export const CLUSTERS_DATA: ClusterSummary[] = [
  {
    id: 0,
    name: 'CD4+ Memory T Cells',
    cell_count: 1500,
    percentage: 34.9,
    dominant_markers: ['CD3D', 'CD3E', 'IL7R', 'LEF1', 'TCF7'],
    batch_entropy: 0.94,
    cell_type: 'T Lymphocyte',
    color: '#06b6d4',
  },
  {
    id: 1,
    name: 'Mature B Lymphocytes',
    cell_count: 1000,
    percentage: 23.3,
    dominant_markers: ['CD19', 'MS4A1', 'CD79A', 'CD79B', 'PAX5'],
    batch_entropy: 0.91,
    cell_type: 'B Lymphocyte',
    color: '#818cf8',
  },
  {
    id: 2,
    name: 'CD14+ Classical Monocytes',
    cell_count: 800,
    percentage: 18.6,
    dominant_markers: ['CD14', 'LYZ', 'S100A8', 'S100A9', 'VCAN'],
    batch_entropy: 0.88,
    cell_type: 'Monocyte/Macrophage',
    color: '#34d399',
  },
  {
    id: 3,
    name: 'Cytotoxic Natural Killer (NK)',
    cell_count: 600,
    percentage: 14.0,
    dominant_markers: ['NKG7', 'GNLY', 'KLRD1', 'KLRB1', 'PRF1'],
    batch_entropy: 0.93,
    cell_type: 'Innate Lymphoid',
    color: '#f59e0b',
  },
  {
    id: 4,
    name: 'Myeloid Dendritic Cells (mDC)',
    cell_count: 400,
    percentage: 9.3,
    dominant_markers: ['FCER1A', 'CLEC10A', 'CD1C', 'HLA-DRA', 'HLA-DQA1'],
    batch_entropy: 0.86,
    cell_type: 'Antigen-Presenting Cell',
    color: '#f43f5e',
  },
];

export const BIOMARKERS_DATA: BiomarkerItem[] = [
  {
    id: 1,
    gene_symbol: 'CD3D',
    cluster_id: 0,
    cluster_name: 'CD4+ Memory T Cells',
    rank: 1,
    composite_score: 0.942,
    log2_fc: 3.45,
    p_value_adj: 1.2e-45,
    roc_auc: 0.985,
    specificity: 0.942,
    prevalence: 0.891,
    prioritization_category: 'Tier 1',
    validation_status: 'Clinically Validated',
    fraction_in_cluster: 0.92,
    fraction_out_cluster: 0.04,
    pathways: ['T-Cell Receptor Signaling', 'Primary Immunodeficiency', 'Cell Adhesion Molecules'],
    druggability: {
      target_class: 'Cell Surface Receptor',
      approved_drugs: ['Muromonab-CD3 (Immunosuppressant)'],
      clinical_phase: 'FDA Approved',
      dgidb_category: 'Druggable Genome Tier 1',
    },
  },
  {
    id: 2,
    gene_symbol: 'CD3E',
    cluster_id: 0,
    cluster_name: 'CD4+ Memory T Cells',
    rank: 2,
    composite_score: 0.928,
    log2_fc: 3.21,
    p_value_adj: 4.5e-42,
    roc_auc: 0.978,
    specificity: 0.931,
    prevalence: 0.885,
    prioritization_category: 'Tier 1',
    validation_status: 'Clinically Validated',
    fraction_in_cluster: 0.89,
    fraction_out_cluster: 0.05,
    pathways: ['T-Cell Receptor Signaling', 'NF-kappa B Signaling'],
    druggability: {
      target_class: 'T-Cell Co-Receptor',
      approved_drugs: ['Teplizumab (Anti-CD3 for T1D)'],
      clinical_phase: 'FDA Approved',
      dgidb_category: 'Druggable Genome Tier 1',
    },
  },
  {
    id: 3,
    gene_symbol: 'MS4A1',
    cluster_id: 1,
    cluster_name: 'Mature B Lymphocytes',
    rank: 1,
    composite_score: 0.965,
    log2_fc: 4.12,
    p_value_adj: 3.1e-52,
    roc_auc: 0.994,
    specificity: 0.982,
    prevalence: 0.945,
    prioritization_category: 'Tier 1',
    validation_status: 'Clinically Validated',
    fraction_in_cluster: 0.96,
    fraction_out_cluster: 0.02,
    pathways: ['B-Cell Receptor Signaling', 'Hematopoietic Cell Lineage'],
    druggability: {
      target_class: 'Tetraspanin / CD20',
      approved_drugs: ['Rituximab', 'Ofatumumab', 'Ocrelizumab'],
      clinical_phase: 'FDA Approved',
      dgidb_category: 'Druggable Genome Tier 1',
    },
  },
  {
    id: 4,
    gene_symbol: 'CD19',
    cluster_id: 1,
    cluster_name: 'Mature B Lymphocytes',
    rank: 2,
    composite_score: 0.951,
    log2_fc: 3.89,
    p_value_adj: 8.7e-49,
    roc_auc: 0.988,
    specificity: 0.974,
    prevalence: 0.928,
    prioritization_category: 'Tier 1',
    validation_status: 'Clinically Validated',
    fraction_in_cluster: 0.93,
    fraction_out_cluster: 0.02,
    pathways: ['B-Cell Receptor Signaling', 'PI3K-Akt Signaling'],
    druggability: {
      target_class: 'Immune Checkpoint / CAR-T Target',
      approved_drugs: ['Tisagenlecleucel (CAR-T)', 'Blinatumomab'],
      clinical_phase: 'FDA Approved',
      dgidb_category: 'Druggable Genome Tier 1',
    },
  },
  {
    id: 5,
    gene_symbol: 'CD14',
    cluster_id: 2,
    cluster_name: 'CD14+ Classical Monocytes',
    rank: 1,
    composite_score: 0.938,
    log2_fc: 3.67,
    p_value_adj: 5.2e-44,
    roc_auc: 0.981,
    specificity: 0.953,
    prevalence: 0.912,
    prioritization_category: 'Tier 1',
    validation_status: 'Clinically Validated',
    fraction_in_cluster: 0.94,
    fraction_out_cluster: 0.06,
    pathways: ['Toll-like Receptor Signaling', 'Phagosome Maturation'],
    druggability: {
      target_class: 'LPS Pattern Recognition Receptor',
      approved_drugs: ['Atorvastatin (Off-target mod)', 'IC14 (Phase II)'],
      clinical_phase: 'Phase II Clinical Trial',
      dgidb_category: 'Druggable Genome Tier 2',
    },
  },
  {
    id: 6,
    gene_symbol: 'LYZ',
    cluster_id: 2,
    cluster_name: 'CD14+ Classical Monocytes',
    rank: 2,
    composite_score: 0.924,
    log2_fc: 3.42,
    p_value_adj: 1.1e-39,
    roc_auc: 0.973,
    specificity: 0.938,
    prevalence: 0.895,
    prioritization_category: 'Tier 1',
    validation_status: 'Literature Validated',
    fraction_in_cluster: 0.91,
    fraction_out_cluster: 0.08,
    pathways: ['Innate Immune System', 'Lysosome Degradation'],
    druggability: {
      target_class: 'Enzyme / Hydrolase',
      approved_drugs: ['Lysozyme Hydrochloride'],
      clinical_phase: 'Approved Topical/Nutraceutical',
      dgidb_category: 'Druggable Genome Tier 3',
    },
  },
  {
    id: 7,
    gene_symbol: 'NKG7',
    cluster_id: 3,
    cluster_name: 'Cytotoxic Natural Killer (NK)',
    rank: 1,
    composite_score: 0.957,
    log2_fc: 4.02,
    p_value_adj: 2.4e-48,
    roc_auc: 0.991,
    specificity: 0.969,
    prevalence: 0.938,
    prioritization_category: 'Tier 1',
    validation_status: 'Clinically Validated',
    fraction_in_cluster: 0.95,
    fraction_out_cluster: 0.07,
    pathways: ['Natural Killer Cell Mediated Cytotoxicity', 'Granule Exocytosis'],
    druggability: {
      target_class: 'Cytotoxic Pore-Forming Granule Protein',
      approved_drugs: ['Investigational NK Cell Engagers'],
      clinical_phase: 'Preclinical Discovery',
      dgidb_category: 'Druggable Genome Tier 2',
    },
  },
  {
    id: 8,
    gene_symbol: 'GNLY',
    cluster_id: 3,
    cluster_name: 'Cytotoxic Natural Killer (NK)',
    rank: 2,
    composite_score: 0.945,
    log2_fc: 3.78,
    p_value_adj: 6.8e-46,
    roc_auc: 0.986,
    specificity: 0.962,
    prevalence: 0.915,
    prioritization_category: 'Tier 1',
    validation_status: 'Clinically Validated',
    fraction_in_cluster: 0.92,
    fraction_out_cluster: 0.05,
    pathways: ['Natural Killer Cell Cytotoxicity', 'Antimicrobial Response'],
    druggability: {
      target_class: 'Cytolytic Antimicrobial Peptide',
      approved_drugs: ['Recombinant Granulysin (Experimental)'],
      clinical_phase: 'Preclinical Discovery',
      dgidb_category: 'Druggable Genome Tier 2',
    },
  },
  {
    id: 9,
    gene_symbol: 'FCER1A',
    cluster_id: 4,
    cluster_name: 'Myeloid Dendritic Cells (mDC)',
    rank: 1,
    composite_score: 0.961,
    log2_fc: 4.25,
    p_value_adj: 1.5e-50,
    roc_auc: 0.993,
    specificity: 0.985,
    prevalence: 0.932,
    prioritization_category: 'Tier 1',
    validation_status: 'Clinically Validated',
    fraction_in_cluster: 0.94,
    fraction_out_cluster: 0.01,
    pathways: ['Fc Epsilon RI Signaling', 'Allergy & Anaphylaxis Pathways'],
    druggability: {
      target_class: 'High Affinity IgE Receptor Alpha',
      approved_drugs: ['Omalizumab (Anti-IgE blocks binding)'],
      clinical_phase: 'FDA Approved Mechanism',
      dgidb_category: 'Druggable Genome Tier 1',
    },
  },
  {
    id: 10,
    gene_symbol: 'CLEC10A',
    cluster_id: 4,
    cluster_name: 'Myeloid Dendritic Cells (mDC)',
    rank: 2,
    composite_score: 0.935,
    log2_fc: 3.55,
    p_value_adj: 7.9e-41,
    roc_auc: 0.979,
    specificity: 0.958,
    prevalence: 0.902,
    prioritization_category: 'Tier 1',
    validation_status: 'Literature Validated',
    fraction_in_cluster: 0.88,
    fraction_out_cluster: 0.02,
    pathways: ['C-Type Lectin Receptor Signaling', 'Antigen Endocytosis'],
    druggability: {
      target_class: 'Endocytic C-Type Lectin Receptor',
      approved_drugs: ['Glycan-conjugated Vaccines (Phase I)'],
      clinical_phase: 'Phase I Clinical Trial',
      dgidb_category: 'Druggable Genome Tier 2',
    },
  },
  {
    id: 11,
    gene_symbol: 'IL7R',
    cluster_id: 0,
    cluster_name: 'CD4+ Memory T Cells',
    rank: 3,
    composite_score: 0.889,
    log2_fc: 2.85,
    p_value_adj: 3.4e-32,
    roc_auc: 0.945,
    specificity: 0.898,
    prevalence: 0.842,
    prioritization_category: 'Tier 2',
    validation_status: 'Literature Validated',
    fraction_in_cluster: 0.84,
    fraction_out_cluster: 0.12,
    pathways: ['JAK-STAT Signaling', 'Cytokine-Cytokine Receptor Interaction'],
    druggability: {
      target_class: 'Interleukin Receptor Alpha Chain',
      approved_drugs: ['Ruxolitinib (Downstream JAK inhibitor)'],
      clinical_phase: 'FDA Approved',
      dgidb_category: 'Druggable Genome Tier 1',
    },
  },
  {
    id: 12,
    gene_symbol: 'S100A8',
    cluster_id: 2,
    cluster_name: 'CD14+ Classical Monocytes',
    rank: 3,
    composite_score: 0.878,
    log2_fc: 2.76,
    p_value_adj: 8.9e-31,
    roc_auc: 0.938,
    specificity: 0.885,
    prevalence: 0.865,
    prioritization_category: 'Tier 2',
    validation_status: 'Literature Validated',
    fraction_in_cluster: 0.87,
    fraction_out_cluster: 0.14,
    pathways: ['Calprotectin Alarmins', 'Neutrophil Extracellular Traps'],
    druggability: {
      target_class: 'Calcium Binding Calgranulin',
      approved_drugs: ['Paquinimod (Phase II Autoimmune)'],
      clinical_phase: 'Phase II Clinical Trial',
      dgidb_category: 'Druggable Genome Tier 2',
    },
  },
];

// DotPlot data for canonical markers across clusters
export const DOTPLOT_DATA: DotPlotItem[] = [
  {
    gene_symbol: 'CD3D',
    clusters: [
      { cluster_id: 0, cluster_name: 'CD4+ Memory T', fraction_expressed: 0.92, mean_expression: 4.5 },
      { cluster_id: 1, cluster_name: 'B Cells', fraction_expressed: 0.02, mean_expression: 0.1 },
      { cluster_id: 2, cluster_name: 'Monocytes', fraction_expressed: 0.04, mean_expression: 0.2 },
      { cluster_id: 3, cluster_name: 'NK Cells', fraction_expressed: 0.15, mean_expression: 0.8 },
      { cluster_id: 4, cluster_name: 'Dendritic Cells', fraction_expressed: 0.01, mean_expression: 0.05 },
    ],
  },
  {
    gene_symbol: 'CD3E',
    clusters: [
      { cluster_id: 0, cluster_name: 'CD4+ Memory T', fraction_expressed: 0.89, mean_expression: 4.2 },
      { cluster_id: 1, cluster_name: 'B Cells', fraction_expressed: 0.01, mean_expression: 0.05 },
      { cluster_id: 2, cluster_name: 'Monocytes', fraction_expressed: 0.03, mean_expression: 0.15 },
      { cluster_id: 3, cluster_name: 'NK Cells', fraction_expressed: 0.12, mean_expression: 0.6 },
      { cluster_id: 4, cluster_name: 'Dendritic Cells', fraction_expressed: 0.02, mean_expression: 0.08 },
    ],
  },
  {
    gene_symbol: 'CD19',
    clusters: [
      { cluster_id: 0, cluster_name: 'CD4+ Memory T', fraction_expressed: 0.01, mean_expression: 0.05 },
      { cluster_id: 1, cluster_name: 'B Cells', fraction_expressed: 0.93, mean_expression: 4.6 },
      { cluster_id: 2, cluster_name: 'Monocytes', fraction_expressed: 0.01, mean_expression: 0.05 },
      { cluster_id: 3, cluster_name: 'NK Cells', fraction_expressed: 0.02, mean_expression: 0.1 },
      { cluster_id: 4, cluster_name: 'Dendritic Cells', fraction_expressed: 0.03, mean_expression: 0.12 },
    ],
  },
  {
    gene_symbol: 'MS4A1',
    clusters: [
      { cluster_id: 0, cluster_name: 'CD4+ Memory T', fraction_expressed: 0.02, mean_expression: 0.08 },
      { cluster_id: 1, cluster_name: 'B Cells', fraction_expressed: 0.96, mean_expression: 4.8 },
      { cluster_id: 2, cluster_name: 'Monocytes', fraction_expressed: 0.01, mean_expression: 0.04 },
      { cluster_id: 3, cluster_name: 'NK Cells', fraction_expressed: 0.01, mean_expression: 0.05 },
      { cluster_id: 4, cluster_name: 'Dendritic Cells', fraction_expressed: 0.02, mean_expression: 0.1 },
    ],
  },
  {
    gene_symbol: 'CD14',
    clusters: [
      { cluster_id: 0, cluster_name: 'CD4+ Memory T', fraction_expressed: 0.03, mean_expression: 0.15 },
      { cluster_id: 1, cluster_name: 'B Cells', fraction_expressed: 0.02, mean_expression: 0.08 },
      { cluster_id: 2, cluster_name: 'Monocytes', fraction_expressed: 0.94, mean_expression: 4.7 },
      { cluster_id: 3, cluster_name: 'NK Cells', fraction_expressed: 0.05, mean_expression: 0.2 },
      { cluster_id: 4, cluster_name: 'Dendritic Cells', fraction_expressed: 0.18, mean_expression: 0.9 },
    ],
  },
  {
    gene_symbol: 'LYZ',
    clusters: [
      { cluster_id: 0, cluster_name: 'CD4+ Memory T', fraction_expressed: 0.05, mean_expression: 0.2 },
      { cluster_id: 1, cluster_name: 'B Cells', fraction_expressed: 0.04, mean_expression: 0.15 },
      { cluster_id: 2, cluster_name: 'Monocytes', fraction_expressed: 0.91, mean_expression: 4.4 },
      { cluster_id: 3, cluster_name: 'NK Cells', fraction_expressed: 0.06, mean_expression: 0.25 },
      { cluster_id: 4, cluster_name: 'Dendritic Cells', fraction_expressed: 0.72, mean_expression: 3.1 },
    ],
  },
  {
    gene_symbol: 'NKG7',
    clusters: [
      { cluster_id: 0, cluster_name: 'CD4+ Memory T', fraction_expressed: 0.22, mean_expression: 1.1 },
      { cluster_id: 1, cluster_name: 'B Cells', fraction_expressed: 0.02, mean_expression: 0.08 },
      { cluster_id: 2, cluster_name: 'Monocytes', fraction_expressed: 0.05, mean_expression: 0.2 },
      { cluster_id: 3, cluster_name: 'NK Cells', fraction_expressed: 0.95, mean_expression: 4.9 },
      { cluster_id: 4, cluster_name: 'Dendritic Cells', fraction_expressed: 0.03, mean_expression: 0.1 },
    ],
  },
  {
    gene_symbol: 'GNLY',
    clusters: [
      { cluster_id: 0, cluster_name: 'CD4+ Memory T', fraction_expressed: 0.18, mean_expression: 0.9 },
      { cluster_id: 1, cluster_name: 'B Cells', fraction_expressed: 0.01, mean_expression: 0.05 },
      { cluster_id: 2, cluster_name: 'Monocytes', fraction_expressed: 0.04, mean_expression: 0.15 },
      { cluster_id: 3, cluster_name: 'NK Cells', fraction_expressed: 0.92, mean_expression: 4.6 },
      { cluster_id: 4, cluster_name: 'Dendritic Cells', fraction_expressed: 0.02, mean_expression: 0.08 },
    ],
  },
  {
    gene_symbol: 'FCER1A',
    clusters: [
      { cluster_id: 0, cluster_name: 'CD4+ Memory T', fraction_expressed: 0.01, mean_expression: 0.04 },
      { cluster_id: 1, cluster_name: 'B Cells', fraction_expressed: 0.01, mean_expression: 0.05 },
      { cluster_id: 2, cluster_name: 'Monocytes', fraction_expressed: 0.06, mean_expression: 0.25 },
      { cluster_id: 3, cluster_name: 'NK Cells', fraction_expressed: 0.01, mean_expression: 0.03 },
      { cluster_id: 4, cluster_name: 'Dendritic Cells', fraction_expressed: 0.94, mean_expression: 4.8 },
    ],
  },
  {
    gene_symbol: 'HLA-DRA',
    clusters: [
      { cluster_id: 0, cluster_name: 'CD4+ Memory T', fraction_expressed: 0.12, mean_expression: 0.6 },
      { cluster_id: 1, cluster_name: 'B Cells', fraction_expressed: 0.88, mean_expression: 4.1 },
      { cluster_id: 2, cluster_name: 'Monocytes', fraction_expressed: 0.85, mean_expression: 3.9 },
      { cluster_id: 3, cluster_name: 'NK Cells', fraction_expressed: 0.08, mean_expression: 0.4 },
      { cluster_id: 4, cluster_name: 'Dendritic Cells', fraction_expressed: 0.98, mean_expression: 4.9 },
    ],
  },
];

// GSEA & Pathway Enrichment for PBMC clusters
export const PATHWAY_ENRICHMENT_DATA: PathwayEnrichment[] = [
  {
    pathway_id: 'H_INTERFERON_GAMMA',
    pathway_name: 'Interferon Gamma (IFN-γ) Hallmark Response',
    source: 'MSigDB Hallmark',
    p_value: 1.4e-14,
    p_value_adj: 2.8e-12,
    overlap_genes: ['CD3D', 'CD3E', 'STAT1', 'IFNG', 'IRF1', 'HLA-DRA', 'CXCL10'],
    cluster_id: 0,
    cluster_name: 'CD4+ Memory T Cells',
  },
  {
    pathway_id: 'KEGG_TCR_SIGNALING',
    pathway_name: 'T-Cell Receptor Signaling Pathway',
    source: 'KEGG',
    p_value: 3.2e-12,
    p_value_adj: 5.1e-10,
    overlap_genes: ['CD3D', 'CD3E', 'CD3G', 'ZAP70', 'LAT', 'LCP2', 'LCK'],
    cluster_id: 0,
    cluster_name: 'CD4+ Memory T Cells',
  },
  {
    pathway_id: 'KEGG_BCR_SIGNALING',
    pathway_name: 'B-Cell Receptor Signaling Cascade',
    source: 'KEGG',
    p_value: 8.5e-16,
    p_value_adj: 1.7e-13,
    overlap_genes: ['CD19', 'MS4A1', 'CD79A', 'CD79B', 'SYK', 'BTK', 'BLNK'],
    cluster_id: 1,
    cluster_name: 'Mature B Lymphocytes',
  },
  {
    pathway_id: 'REACTOME_ANTIGEN_PROCESSING',
    pathway_name: 'MHC Class II Antigen Presentation',
    source: 'Reactome',
    p_value: 4.1e-15,
    p_value_adj: 6.2e-13,
    overlap_genes: ['HLA-DRA', 'HLA-DQA1', 'HLA-DQB1', 'CD74', 'CTSS'],
    cluster_id: 1,
    cluster_name: 'Mature B Lymphocytes',
  },
  {
    pathway_id: 'H_INFLAMMATORY_RESPONSE',
    pathway_name: 'Hallmark Inflammatory & Alarm Response',
    source: 'MSigDB Hallmark',
    p_value: 2.1e-13,
    p_value_adj: 3.8e-11,
    overlap_genes: ['CD14', 'S100A8', 'S100A9', 'LYZ', 'IL1B', 'TNF', 'CCL2'],
    cluster_id: 2,
    cluster_name: 'CD14+ Classical Monocytes',
  },
  {
    pathway_id: 'KEGG_NK_CYTOTOXICITY',
    pathway_name: 'Natural Killer Cell Mediated Cytotoxicity',
    source: 'KEGG',
    p_value: 6.7e-18,
    p_value_adj: 1.3e-15,
    overlap_genes: ['NKG7', 'GNLY', 'PRF1', 'GZMB', 'KLRD1', 'FCGR3A'],
    cluster_id: 3,
    cluster_name: 'Cytotoxic Natural Killer (NK)',
  },
  {
    pathway_id: 'REACTOME_DENDRITIC_CELL_MIGRATION',
    pathway_name: 'DC Maturation & Lymph Node Trafficking',
    source: 'Reactome',
    p_value: 5.3e-11,
    p_value_adj: 8.4e-9,
    overlap_genes: ['FCER1A', 'CLEC10A', 'CD1C', 'CCR7', 'ITGAX'],
    cluster_id: 4,
    cluster_name: 'Myeloid Dendritic Cells (mDC)',
  },
];

// Single Cell Details for inspector drawer
export const SAMPLE_CELL_DETAILS: Record<string, SingleCellDetail> = {
  'cell_00042': {
    barcode: 'AAACCTGAGATACT-1',
    cluster_id: 0,
    cluster_name: 'CD4+ Memory T Cells',
    cell_type: 'T Lymphocyte',
    total_counts: 5240,
    detected_genes: 1480,
    mito_percent: 2.85,
    cell_cycle_phase: 'G1',
    top_markers: [
      { gene: 'CD3D', expression: 4.82 },
      { gene: 'CD3E', expression: 4.31 },
      { gene: 'IL7R', expression: 3.95 },
      { gene: 'LEF1', expression: 3.12 },
      { gene: 'TCF7', expression: 2.84 },
    ],
    batch: 'Batch_01',
    condition: 'Healthy Donor Control',
  },
  'cell_01280': {
    barcode: 'AAAGTAGCATTCGA-1',
    cluster_id: 1,
    cluster_name: 'Mature B Lymphocytes',
    cell_type: 'B Lymphocyte',
    total_counts: 6180,
    detected_genes: 1620,
    mito_percent: 3.12,
    cell_cycle_phase: 'S',
    top_markers: [
      { gene: 'MS4A1', expression: 5.12 },
      { gene: 'CD19', expression: 4.78 },
      { gene: 'CD79A', expression: 4.45 },
      { gene: 'PAX5', expression: 3.89 },
      { gene: 'BANK1', expression: 3.25 },
    ],
    batch: 'Batch_02',
    condition: 'Healthy Donor Control',
  },
  'cell_02450': {
    barcode: 'AACCATGTCATAGG-1',
    cluster_id: 2,
    cluster_name: 'CD14+ Classical Monocytes',
    cell_type: 'Monocyte/Macrophage',
    total_counts: 7420,
    detected_genes: 1890,
    mito_percent: 4.05,
    cell_cycle_phase: 'G1',
    top_markers: [
      { gene: 'CD14', expression: 5.41 },
      { gene: 'LYZ', expression: 4.95 },
      { gene: 'S100A8', expression: 4.62 },
      { gene: 'S100A9', expression: 4.38 },
      { gene: 'VCAN', expression: 3.91 },
    ],
    batch: 'Batch_01',
    condition: 'Healthy Donor Control',
  },
  'cell_03210': {
    barcode: 'AACGTTGCACACGT-1',
    cluster_id: 3,
    cluster_name: 'Cytotoxic Natural Killer (NK)',
    cell_type: 'Innate Lymphoid',
    total_counts: 5890,
    detected_genes: 1540,
    mito_percent: 3.48,
    cell_cycle_phase: 'G2/M',
    top_markers: [
      { gene: 'NKG7', expression: 5.32 },
      { gene: 'GNLY', expression: 4.88 },
      { gene: 'PRF1', expression: 4.41 },
      { gene: 'KLRD1', expression: 4.15 },
      { gene: 'GZMB', expression: 3.82 },
    ],
    batch: 'Batch_03',
    condition: 'Healthy Donor Control',
  },
};

// ============================================================================
// Synthetic Cell Embeddings Generator (Deterministic & Reproducible)
// ============================================================================

function generateClusterPoints(
  count: number,
  clusterId: number,
  cellType: string,
  centerX: number,
  centerY: number,
  spreadX: number,
  spreadY: number,
  seed: number
): CellPoint[] {
  const points: CellPoint[] = [];
  const batches = ['Batch_01', 'Batch_02', 'Batch_03'];
  const conditions = ['Control', 'Stimulated'];
  const phases: ('G1' | 'S' | 'G2/M')[] = ['G1', 'S', 'G2/M'];

  let s = seed;
  const rand = () => {
    s = (s * 9301 + 49297) % 233280;
    return s / 233280;
  };

  const randNorm = () => {
    const u = Math.max(1e-9, rand());
    const v = rand();
    return Math.sqrt(-2.0 * Math.log(u)) * Math.cos(2.0 * Math.PI * v);
  };

  for (let i = 0; i < count; i++) {
    const angle = rand() * Math.PI * 2;
    const r = Math.sqrt(rand());
    const nx = randNorm() * 0.35;
    const ny = randNorm() * 0.35;

    const x = centerX + Math.cos(angle) * r * spreadX + nx;
    const y = centerY + Math.sin(angle) * r * spreadY + ny;

    points.push({
      id: `cell_${clusterId}_${i.toString().padStart(4, '0')}`,
      x: Math.round(x * 100) / 100,
      y: Math.round(y * 100) / 100,
      cluster: clusterId,
      cell_type: cellType,
      batch: batches[Math.floor(rand() * batches.length)],
      condition: conditions[Math.floor(rand() * conditions.length)],
      expression: Math.round(rand() * 100) / 100,
      cell_cycle: phases[Math.floor(rand() * phases.length)],
      umi_count: Math.round(3000 + rand() * 5000),
      gene_count: Math.round(800 + rand() * 1400),
      mito_pct: Math.round((1.5 + rand() * 4.5) * 10) / 10,
    });
  }

  return points;
}

export function buildEmbeddings() {
  // Hybrid UMAP: Well separated clusters with preserved global geometry
  const hybrid = [
    ...generateClusterPoints(140, 0, 'CD4+ Memory T', -5.2, 4.1, 1.6, 1.4, 101),
    ...generateClusterPoints(110, 1, 'Mature B Cells', 6.8, 3.2, 1.5, 1.6, 202),
    ...generateClusterPoints(95, 2, 'Monocytes', -4.5, -5.8, 1.8, 1.5, 303),
    ...generateClusterPoints(80, 3, 'NK Cells', -1.2, 7.4, 1.3, 1.2, 404),
    ...generateClusterPoints(55, 4, 'Dendritic Cells', 5.1, -4.6, 1.2, 1.3, 505),
  ];

  // Direct UMAP: Distorted geometry, scattered points
  const direct = [
    ...generateClusterPoints(140, 0, 'CD4+ Memory T', -8.1, -2.5, 2.2, 2.5, 606),
    ...generateClusterPoints(110, 1, 'Mature B Cells', 2.4, 8.9, 2.8, 2.1, 707),
    ...generateClusterPoints(95, 2, 'Monocytes', 7.9, -6.1, 2.5, 2.9, 808),
    ...generateClusterPoints(80, 3, 'NK Cells', -4.1, 5.8, 2.6, 2.4, 909),
    ...generateClusterPoints(55, 4, 'Dendritic Cells', 0.2, -1.8, 3.1, 2.8, 1010),
  ];

  // PCA (PC1 vs PC2): Linear projection, overlapping continuous clouds
  const pca = [
    ...generateClusterPoints(140, 0, 'CD4+ Memory T', -12.4, 6.2, 5.2, 4.8, 1111),
    ...generateClusterPoints(110, 1, 'Mature B Cells', 14.8, 4.1, 6.1, 5.2, 1212),
    ...generateClusterPoints(95, 2, 'Monocytes', -8.9, -11.2, 5.8, 4.9, 1313),
    ...generateClusterPoints(80, 3, 'NK Cells', -3.2, 12.8, 4.5, 4.2, 1414),
    ...generateClusterPoints(55, 4, 'Dendritic Cells', 4.1, -8.6, 4.2, 3.8, 1515),
  ];

  return { hybrid, direct, pca };
}

export const EMBEDDINGS_DATA = buildEmbeddings();

// ============================================================================
// Cohort Data Registry: Dynamically Provides Full Data per Selected Cohort
// ============================================================================

export interface CohortCompleteData {
  cohort: DatasetCohort;
  experiment: ExperimentMetadata;
  steps: PipelineStepStatus[];
  benchmarks: Record<string, TopologyBenchmark>;
  qc: QCSummary;
  clusters: ClusterSummary[];
  biomarkers: BiomarkerItem[];
  dotplot: DotPlotItem[];
  pathways: PathwayEnrichment[];
  embeddings: {
    hybrid: CellPoint[];
    direct: CellPoint[];
    pca: CellPoint[];
  };
}

export const COHORTS_DATA_REGISTRY: Record<string, CohortCompleteData> = {
  pbmc3k: {
    cohort: DATASET_COHORTS[0],
    experiment: INITIAL_EXPERIMENT,
    steps: INITIAL_PIPELINE_STEPS,
    benchmarks: TOPOLOGY_BENCHMARKS,
    qc: QC_METRICS,
    clusters: CLUSTERS_DATA,
    biomarkers: BIOMARKERS_DATA,
    dotplot: DOTPLOT_DATA,
    pathways: PATHWAY_ENRICHMENT_DATA,
    embeddings: EMBEDDINGS_DATA,
  },
  gbm_tme: {
    cohort: DATASET_COHORTS[1],
    experiment: {
      id: 2,
      name: 'Glioblastoma Multiforme TME & Infiltration Study',
      description: 'Single-cell dissection of high-grade IDH-wildtype glioblastoma microenvironment and stemness gradients.',
      dataset_name: 'GBM_Neoplastic_TME_v2.h5ad',
      created_at: '2026-09-10 11:15:00 UTC',
      status: 'completed',
      cell_count: 3450,
      gene_count: 2420,
    },
    steps: [
      { id: 1, step: 'qc', status: 'completed', progress: 100, completed_at: '11:16:02' },
      { id: 2, step: 'preprocess', status: 'completed', progress: 100, completed_at: '11:16:45' },
      { id: 3, step: 'pca', status: 'completed', progress: 100, completed_at: '11:17:30' },
      { id: 4, step: 'umap', status: 'completed', progress: 100, completed_at: '11:18:48' },
      { id: 5, step: 'cluster', status: 'completed', progress: 100, completed_at: '11:19:25' },
      { id: 6, step: 'de', status: 'completed', progress: 100, completed_at: '11:20:50' },
      { id: 7, step: 'biomarkers', status: 'completed', progress: 100, completed_at: '11:21:40' },
    ],
    benchmarks: {
      hybrid: {
        method: 'Hybrid PCA → UMAP (CellMap)',
        knn_preservation: 0.891,
        trustworthiness: 0.948,
        continuity: 0.966,
        runtime_seconds: 4.12,
        visualization_latency_ms: 4120,
        global_distance_correlation: 0.762,
        dual_objective_score: 0.934,
      },
      direct: {
        method: 'Direct UMAP (Raw HVG)',
        knn_preservation: 0.682,
        trustworthiness: 0.854,
        continuity: 0.805,
        runtime_seconds: 12.8,
        visualization_latency_ms: 12800,
        global_distance_correlation: 0.364,
        dual_objective_score: 0.755,
      },
      pca: {
        method: 'Principal Component Analysis (PC1 vs PC2)',
        knn_preservation: 0.635,
        trustworthiness: 0.921,
        continuity: 0.898,
        runtime_seconds: 0.58,
        visualization_latency_ms: 580,
        global_distance_correlation: 0.835,
        dual_objective_score: 0.869,
      },
    },
    qc: {
      cells_before: 3750,
      cells_after: 3450,
      genes_before: 2420,
      genes_after: 2350,
      median_counts: 8640,
      median_genes: 2150,
      median_mito_pct: 4.12,
      doublet_rate_pct: 4.2,
      low_quality_dropped: 210,
      apoptotic_dropped: 90,
    },
    clusters: [
      {
        id: 0,
        name: 'Glioblastoma Stem-like Cells (GSC)',
        cell_count: 1250,
        percentage: 36.2,
        dominant_markers: ['SOX2', 'EGFR', 'NES', 'PROM1', 'OLIG2'],
        batch_entropy: 0.95,
        cell_type: 'Neoplastic Stem Cell',
        color: '#c084fc',
      },
      {
        id: 1,
        name: 'Tumor-Associated Macrophages (TAM)',
        cell_count: 980,
        percentage: 28.4,
        dominant_markers: ['CD68', 'AIF1', 'ITGAM', 'MRC1', 'TGFB1'],
        batch_entropy: 0.92,
        cell_type: 'Myeloid Infiltrate',
        color: '#f43f5e',
      },
      {
        id: 2,
        name: 'Reactive Astrocytes',
        cell_count: 620,
        percentage: 18.0,
        dominant_markers: ['GFAP', 'ALDH1L1', 'AQP4', 'S100B', 'SLC1A3'],
        batch_entropy: 0.89,
        cell_type: 'Glial Stroma',
        color: '#34d399',
      },
      {
        id: 3,
        name: 'Oligodendrocytes',
        cell_count: 380,
        percentage: 11.0,
        dominant_markers: ['MBP', 'MOG', 'PLP1', 'CNP', 'SOX10'],
        batch_entropy: 0.88,
        cell_type: 'Glial Myelinating',
        color: '#38bdf8',
      },
      {
        id: 4,
        name: 'Tumor Endothelial Cells',
        cell_count: 220,
        percentage: 6.4,
        dominant_markers: ['PECAM1', 'VWF', 'CD34', 'FLT1', 'KDR'],
        batch_entropy: 0.85,
        cell_type: 'Vascular Endothelium',
        color: '#fbbf24',
      },
    ],
    biomarkers: [
      {
        id: 201,
        gene_symbol: 'EGFR',
        cluster_id: 0,
        cluster_name: 'Glioblastoma Stem-like Cells (GSC)',
        rank: 1,
        composite_score: 0.978,
        log2_fc: 4.85,
        p_value_adj: 2.1e-62,
        roc_auc: 0.995,
        specificity: 0.984,
        prevalence: 0.952,
        prioritization_category: 'Tier 1',
        validation_status: 'Clinically Validated',
        fraction_in_cluster: 0.96,
        fraction_out_cluster: 0.03,
        pathways: ['EGFR Tyrosine Kinase Inhibitor Resistance', 'Glioma Signaling', 'PI3K-Akt Pathway'],
        druggability: {
          target_class: 'Receptor Tyrosine Kinase',
          approved_drugs: ['Osimertinib', 'Gefitinib', 'Erlotinib'],
          clinical_phase: 'FDA Approved',
          dgidb_category: 'Druggable Genome Tier 1',
        },
      },
      {
        id: 202,
        gene_symbol: 'SOX2',
        cluster_id: 0,
        cluster_name: 'Glioblastoma Stem-like Cells (GSC)',
        rank: 2,
        composite_score: 0.964,
        log2_fc: 4.12,
        p_value_adj: 8.4e-55,
        roc_auc: 0.989,
        specificity: 0.971,
        prevalence: 0.935,
        prioritization_category: 'Tier 1',
        validation_status: 'Literature Validated',
        fraction_in_cluster: 0.94,
        fraction_out_cluster: 0.04,
        pathways: ['Pluripotency Stem Cell Maintenance', 'Wnt / Notch Signaling'],
        druggability: {
          target_class: 'HMG-box Transcription Factor',
          approved_drugs: ['Investigational Epigenetic Degraders (PROTAC)'],
          clinical_phase: 'Preclinical Discovery',
          dgidb_category: 'Druggable Genome Tier 3',
        },
      },
      {
        id: 203,
        gene_symbol: 'CD68',
        cluster_id: 1,
        cluster_name: 'Tumor-Associated Macrophages (TAM)',
        rank: 1,
        composite_score: 0.952,
        log2_fc: 3.95,
        p_value_adj: 1.6e-48,
        roc_auc: 0.988,
        specificity: 0.965,
        prevalence: 0.925,
        prioritization_category: 'Tier 1',
        validation_status: 'Clinically Validated',
        fraction_in_cluster: 0.93,
        fraction_out_cluster: 0.05,
        pathways: ['Phagocytosis', 'Macrophage Polarization M2'],
        druggability: {
          target_class: 'Scavenger Receptor Glycoprotein',
          approved_drugs: ['Anti-CD68 Targeted Conjugates'],
          clinical_phase: 'Phase I Clinical Trial',
          dgidb_category: 'Druggable Genome Tier 2',
        },
      },
      {
        id: 204,
        gene_symbol: 'GFAP',
        cluster_id: 2,
        cluster_name: 'Reactive Astrocytes',
        rank: 1,
        composite_score: 0.961,
        log2_fc: 4.35,
        p_value_adj: 5.3e-52,
        roc_auc: 0.992,
        specificity: 0.978,
        prevalence: 0.941,
        prioritization_category: 'Tier 1',
        validation_status: 'Clinically Validated',
        fraction_in_cluster: 0.95,
        fraction_out_cluster: 0.03,
        pathways: ['Astrocyte Reactivity', 'Intermediate Filament Assembly'],
        druggability: {
          target_class: 'Type III Intermediate Filament',
          approved_drugs: ['Diagnostic Serum Biomarker (FDA cleared)'],
          clinical_phase: 'Diagnostic Approved',
          dgidb_category: 'Biomarker Target',
        },
      },
    ],
    dotplot: [
      {
        gene_symbol: 'EGFR',
        clusters: [
          { cluster_id: 0, cluster_name: 'GSC', fraction_expressed: 0.96, mean_expression: 4.9 },
          { cluster_id: 1, cluster_name: 'TAM', fraction_expressed: 0.03, mean_expression: 0.1 },
          { cluster_id: 2, cluster_name: 'Astrocytes', fraction_expressed: 0.12, mean_expression: 0.6 },
          { cluster_id: 3, cluster_name: 'Oligo', fraction_expressed: 0.01, mean_expression: 0.05 },
          { cluster_id: 4, cluster_name: 'Endothelial', fraction_expressed: 0.05, mean_expression: 0.2 },
        ],
      },
      {
        gene_symbol: 'SOX2',
        clusters: [
          { cluster_id: 0, cluster_name: 'GSC', fraction_expressed: 0.94, mean_expression: 4.7 },
          { cluster_id: 1, cluster_name: 'TAM', fraction_expressed: 0.02, mean_expression: 0.08 },
          { cluster_id: 2, cluster_name: 'Astrocytes', fraction_expressed: 0.15, mean_expression: 0.7 },
          { cluster_id: 3, cluster_name: 'Oligo', fraction_expressed: 0.08, mean_expression: 0.4 },
          { cluster_id: 4, cluster_name: 'Endothelial', fraction_expressed: 0.01, mean_expression: 0.05 },
        ],
      },
      {
        gene_symbol: 'CD68',
        clusters: [
          { cluster_id: 0, cluster_name: 'GSC', fraction_expressed: 0.05, mean_expression: 0.2 },
          { cluster_id: 1, cluster_name: 'TAM', fraction_expressed: 0.93, mean_expression: 4.8 },
          { cluster_id: 2, cluster_name: 'Astrocytes', fraction_expressed: 0.04, mean_expression: 0.15 },
          { cluster_id: 3, cluster_name: 'Oligo', fraction_expressed: 0.02, mean_expression: 0.08 },
          { cluster_id: 4, cluster_name: 'Endothelial', fraction_expressed: 0.06, mean_expression: 0.25 },
        ],
      },
      {
        gene_symbol: 'GFAP',
        clusters: [
          { cluster_id: 0, cluster_name: 'GSC', fraction_expressed: 0.18, mean_expression: 0.9 },
          { cluster_id: 1, cluster_name: 'TAM', fraction_expressed: 0.02, mean_expression: 0.06 },
          { cluster_id: 2, cluster_name: 'Astrocytes', fraction_expressed: 0.95, mean_expression: 4.9 },
          { cluster_id: 3, cluster_name: 'Oligo', fraction_expressed: 0.04, mean_expression: 0.15 },
          { cluster_id: 4, cluster_name: 'Endothelial', fraction_expressed: 0.01, mean_expression: 0.04 },
        ],
      },
      {
        gene_symbol: 'PECAM1',
        clusters: [
          { cluster_id: 0, cluster_name: 'GSC', fraction_expressed: 0.01, mean_expression: 0.05 },
          { cluster_id: 1, cluster_name: 'TAM', fraction_expressed: 0.04, mean_expression: 0.18 },
          { cluster_id: 2, cluster_name: 'Astrocytes', fraction_expressed: 0.02, mean_expression: 0.08 },
          { cluster_id: 3, cluster_name: 'Oligo', fraction_expressed: 0.01, mean_expression: 0.04 },
          { cluster_id: 4, cluster_name: 'Endothelial', fraction_expressed: 0.97, mean_expression: 4.9 },
        ],
      },
    ],
    pathways: [
      {
        pathway_id: 'H_GLIOMA_STEMNESS',
        pathway_name: 'Glioma Stemness & Notch/Wnt Signaling',
        source: 'MSigDB Hallmark',
        p_value: 2.1e-16,
        p_value_adj: 4.2e-14,
        overlap_genes: ['SOX2', 'EGFR', 'PROM1', 'NES', 'NOTCH1', 'HES1'],
        cluster_id: 0,
        cluster_name: 'Glioblastoma Stem-like Cells (GSC)',
      },
      {
        pathway_id: 'KEGG_TAM_IMMUNOSUPPRESSION',
        pathway_name: 'Macrophage M2 Polarization & Immunosuppression',
        source: 'KEGG',
        p_value: 5.4e-14,
        p_value_adj: 8.8e-12,
        overlap_genes: ['CD68', 'TGFB1', 'MRC1', 'ARG1', 'IL10', 'VEGFA'],
        cluster_id: 1,
        cluster_name: 'Tumor-Associated Macrophages (TAM)',
      },
    ],
    embeddings: {
      hybrid: [
        ...generateClusterPoints(130, 0, 'GSC', -4.2, 5.5, 1.7, 1.6, 2101),
        ...generateClusterPoints(100, 1, 'TAM', 5.8, -3.2, 1.8, 1.5, 2202),
        ...generateClusterPoints(80, 2, 'Astrocytes', -6.1, -4.8, 1.4, 1.3, 2303),
        ...generateClusterPoints(60, 3, 'Oligo', 4.5, 6.2, 1.3, 1.2, 2404),
        ...generateClusterPoints(40, 4, 'Endothelial', 0.8, -7.5, 1.1, 1.1, 2505),
      ],
      direct: [
        ...generateClusterPoints(130, 0, 'GSC', -6.5, 2.1, 2.5, 2.8, 2606),
        ...generateClusterPoints(100, 1, 'TAM', 4.1, 6.8, 2.9, 2.4, 2707),
        ...generateClusterPoints(80, 2, 'Astrocytes', -3.2, -6.5, 2.6, 2.3, 2808),
        ...generateClusterPoints(60, 3, 'Oligo', 6.8, -2.1, 2.4, 2.6, 2909),
        ...generateClusterPoints(40, 4, 'Endothelial', -0.5, 0.4, 3.2, 2.9, 3010),
      ],
      pca: [
        ...generateClusterPoints(130, 0, 'GSC', -14.2, 8.1, 5.5, 5.1, 3111),
        ...generateClusterPoints(100, 1, 'TAM', 12.8, -7.4, 6.2, 5.4, 3212),
        ...generateClusterPoints(80, 2, 'Astrocytes', -9.5, -9.8, 5.1, 4.8, 3313),
        ...generateClusterPoints(60, 3, 'Oligo', 8.2, 11.4, 4.8, 4.3, 3414),
        ...generateClusterPoints(40, 4, 'Endothelial', 2.1, -12.5, 4.1, 3.6, 3515),
      ],
    },
  },
  pancreas_islets: {
    cohort: DATASET_COHORTS[2],
    experiment: {
      id: 3,
      name: 'Human Pancreatic Islets Endocrine Dissection',
      description: 'Single-cell profiling of pancreatic islets identifying glucagon (GCG) and insulin (INS) hormone-producing clusters.',
      dataset_name: 'Pancreas_Endocrine_Atlas_v1.h5ad',
      created_at: '2026-09-12 09:40:00 UTC',
      status: 'completed',
      cell_count: 2850,
      gene_count: 1980,
    },
    steps: [
      { id: 1, step: 'qc', status: 'completed', progress: 100, completed_at: '09:41:10' },
      { id: 2, step: 'preprocess', status: 'completed', progress: 100, completed_at: '09:42:01' },
      { id: 3, step: 'pca', status: 'completed', progress: 100, completed_at: '09:42:40' },
      { id: 4, step: 'umap', status: 'completed', progress: 100, completed_at: '09:43:55' },
      { id: 5, step: 'cluster', status: 'completed', progress: 100, completed_at: '09:44:30' },
      { id: 6, step: 'de', status: 'completed', progress: 100, completed_at: '09:45:45' },
      { id: 7, step: 'biomarkers', status: 'completed', progress: 100, completed_at: '09:46:25' },
    ],
    benchmarks: {
      hybrid: {
        method: 'Hybrid PCA → UMAP (CellMap)',
        knn_preservation: 0.895,
        trustworthiness: 0.951,
        continuity: 0.969,
        runtime_seconds: 3.85,
        visualization_latency_ms: 3850,
        global_distance_correlation: 0.774,
        dual_objective_score: 0.941,
      },
      direct: {
        method: 'Direct UMAP (Raw HVG)',
        knn_preservation: 0.712,
        trustworthiness: 0.871,
        continuity: 0.819,
        runtime_seconds: 11.2,
        visualization_latency_ms: 11200,
        global_distance_correlation: 0.392,
        dual_objective_score: 0.781,
      },
      pca: {
        method: 'Principal Component Analysis (PC1 vs PC2)',
        knn_preservation: 0.628,
        trustworthiness: 0.918,
        continuity: 0.896,
        runtime_seconds: 0.52,
        visualization_latency_ms: 520,
        global_distance_correlation: 0.829,
        dual_objective_score: 0.864,
      },
    },
    qc: {
      cells_before: 3100,
      cells_after: 2850,
      genes_before: 1980,
      genes_after: 1920,
      median_counts: 3950,
      median_genes: 1120,
      median_mito_pct: 2.95,
      doublet_rate_pct: 3.1,
      low_quality_dropped: 180,
      apoptotic_dropped: 70,
    },
    clusters: [
      {
        id: 0,
        name: 'Beta Cells (Insulin-producing)',
        cell_count: 1100,
        percentage: 38.6,
        dominant_markers: ['INS', 'IAPP', 'MAFA', 'SLC30A8', 'PDX1'],
        batch_entropy: 0.93,
        cell_type: 'Endocrine Beta',
        color: '#10b981',
      },
      {
        id: 1,
        name: 'Alpha Cells (Glucagon-producing)',
        cell_count: 850,
        percentage: 29.8,
        dominant_markers: ['GCG', 'TTR', 'ARX', 'IRX2', 'DPP4'],
        batch_entropy: 0.91,
        cell_type: 'Endocrine Alpha',
        color: '#f59e0b',
      },
      {
        id: 2,
        name: 'Delta Cells (Somatostatin)',
        cell_count: 420,
        percentage: 14.7,
        dominant_markers: ['SST', 'HHEX', 'LEPR', 'RBP4'],
        batch_entropy: 0.89,
        cell_type: 'Endocrine Delta',
        color: '#6366f1',
      },
      {
        id: 3,
        name: 'Acinar Exocrine Cells',
        cell_count: 320,
        percentage: 11.2,
        dominant_markers: ['PRSS1', 'CPA1', 'CLPS', 'REG1A'],
        batch_entropy: 0.87,
        cell_type: 'Exocrine Acinar',
        color: '#ec4899',
      },
      {
        id: 4,
        name: 'Ductal Cells',
        cell_count: 160,
        percentage: 5.6,
        dominant_markers: ['KRT19', 'SOX9', 'CFTR', 'MMP7'],
        batch_entropy: 0.84,
        cell_type: 'Exocrine Ductal',
        color: '#06b6d4',
      },
    ],
    biomarkers: [
      {
        id: 301,
        gene_symbol: 'INS',
        cluster_id: 0,
        cluster_name: 'Beta Cells (Insulin-producing)',
        rank: 1,
        composite_score: 0.992,
        log2_fc: 5.82,
        p_value_adj: 1.1e-75,
        roc_auc: 0.999,
        specificity: 0.995,
        prevalence: 0.985,
        prioritization_category: 'Tier 1',
        validation_status: 'Clinically Validated',
        fraction_in_cluster: 0.99,
        fraction_out_cluster: 0.01,
        pathways: ['Insulin Secretion Pathway', 'Maturity Onset Diabetes of the Young (MODY)', 'Type II Diabetes'],
        druggability: {
          target_class: 'Hormone / Peptide',
          approved_drugs: ['Recombinant Human Insulin', 'Insulin Glargine', 'Insulin Lispro'],
          clinical_phase: 'FDA Approved',
          dgidb_category: 'Druggable Genome Tier 1',
        },
      },
      {
        id: 302,
        gene_symbol: 'GCG',
        cluster_id: 1,
        cluster_name: 'Alpha Cells (Glucagon-producing)',
        rank: 1,
        composite_score: 0.985,
        log2_fc: 5.41,
        p_value_adj: 4.8e-68,
        roc_auc: 0.997,
        specificity: 0.991,
        prevalence: 0.975,
        prioritization_category: 'Tier 1',
        validation_status: 'Clinically Validated',
        fraction_in_cluster: 0.98,
        fraction_out_cluster: 0.01,
        pathways: ['Glucagon Signaling Pathway', 'Carbohydrate Digestion and Absorption'],
        druggability: {
          target_class: 'Peptide Hormone',
          approved_drugs: ['Glucagon Emergency Injection', 'Dasiglucagon'],
          clinical_phase: 'FDA Approved',
          dgidb_category: 'Druggable Genome Tier 1',
        },
      },
    ],
    dotplot: [
      {
        gene_symbol: 'INS',
        clusters: [
          { cluster_id: 0, cluster_name: 'Beta', fraction_expressed: 0.99, mean_expression: 5.0 },
          { cluster_id: 1, cluster_name: 'Alpha', fraction_expressed: 0.01, mean_expression: 0.04 },
          { cluster_id: 2, cluster_name: 'Delta', fraction_expressed: 0.02, mean_expression: 0.08 },
          { cluster_id: 3, cluster_name: 'Acinar', fraction_expressed: 0.01, mean_expression: 0.02 },
          { cluster_id: 4, cluster_name: 'Ductal', fraction_expressed: 0.01, mean_expression: 0.03 },
        ],
      },
      {
        gene_symbol: 'GCG',
        clusters: [
          { cluster_id: 0, cluster_name: 'Beta', fraction_expressed: 0.01, mean_expression: 0.05 },
          { cluster_id: 1, cluster_name: 'Alpha', fraction_expressed: 0.98, mean_expression: 5.0 },
          { cluster_id: 2, cluster_name: 'Delta', fraction_expressed: 0.02, mean_expression: 0.07 },
          { cluster_id: 3, cluster_name: 'Acinar', fraction_expressed: 0.01, mean_expression: 0.03 },
          { cluster_id: 4, cluster_name: 'Ductal', fraction_expressed: 0.01, mean_expression: 0.02 },
        ],
      },
      {
        gene_symbol: 'SST',
        clusters: [
          { cluster_id: 0, cluster_name: 'Beta', fraction_expressed: 0.02, mean_expression: 0.08 },
          { cluster_id: 1, cluster_name: 'Alpha', fraction_expressed: 0.03, mean_expression: 0.12 },
          { cluster_id: 2, cluster_name: 'Delta', fraction_expressed: 0.96, mean_expression: 4.8 },
          { cluster_id: 3, cluster_name: 'Acinar', fraction_expressed: 0.01, mean_expression: 0.04 },
          { cluster_id: 4, cluster_name: 'Ductal', fraction_expressed: 0.01, mean_expression: 0.03 },
        ],
      },
    ],
    pathways: [
      {
        pathway_id: 'KEGG_INSULIN_SECRETION',
        pathway_name: 'Insulin Synthesis and Granule Exocytosis',
        source: 'KEGG',
        p_value: 1.2e-22,
        p_value_adj: 2.4e-20,
        overlap_genes: ['INS', 'IAPP', 'PDX1', 'MAFA', 'SLC30A8', 'ABCC8', 'KCNJ11'],
        cluster_id: 0,
        cluster_name: 'Beta Cells (Insulin-producing)',
      },
    ],
    embeddings: {
      hybrid: [
        ...generateClusterPoints(120, 0, 'Beta Cells', -6.1, 3.8, 1.6, 1.5, 4101),
        ...generateClusterPoints(100, 1, 'Alpha Cells', 5.4, 4.2, 1.7, 1.4, 4202),
        ...generateClusterPoints(60, 2, 'Delta Cells', 0.2, 6.8, 1.2, 1.2, 4303),
        ...generateClusterPoints(50, 3, 'Acinar', -3.8, -6.5, 1.5, 1.4, 4404),
        ...generateClusterPoints(30, 4, 'Ductal', 6.2, -5.1, 1.2, 1.1, 4505),
      ],
      direct: [
        ...generateClusterPoints(120, 0, 'Beta Cells', -7.2, -1.8, 2.6, 2.5, 4606),
        ...generateClusterPoints(100, 1, 'Alpha Cells', 4.1, 7.8, 2.8, 2.3, 4707),
        ...generateClusterPoints(60, 2, 'Delta Cells', -1.2, 2.5, 3.1, 2.6, 4808),
        ...generateClusterPoints(50, 3, 'Acinar', 7.5, -4.2, 2.4, 2.7, 4909),
        ...generateClusterPoints(30, 4, 'Ductal', 0.5, -8.1, 2.9, 2.5, 5010),
      ],
      pca: [
        ...generateClusterPoints(120, 0, 'Beta Cells', -13.5, 6.5, 5.6, 5.0, 5111),
        ...generateClusterPoints(100, 1, 'Alpha Cells', 11.2, 7.8, 5.8, 5.1, 5212),
        ...generateClusterPoints(60, 2, 'Delta Cells', 1.5, 12.1, 4.5, 4.2, 5313),
        ...generateClusterPoints(50, 3, 'Acinar', -8.1, -10.5, 5.1, 4.6, 5414),
        ...generateClusterPoints(30, 4, 'Ductal', 8.5, -8.2, 4.2, 3.8, 5515),
      ],
    },
  },
  covid_balf: {
    cohort: DATASET_COHORTS[3],
    experiment: {
      id: 4,
      name: 'COVID-19 Bronchoalveolar Inflammatory Cascade',
      description: 'Single-cell profiling of bronchoalveolar lavage fluid in critical COVID-19 respiratory distress patients.',
      dataset_name: 'COVID19_BALF_Severe_v1.h5ad',
      created_at: '2026-09-13 16:20:00 UTC',
      status: 'completed',
      cell_count: 3820,
      gene_count: 2240,
    },
    steps: [
      { id: 1, step: 'qc', status: 'completed', progress: 100, completed_at: '16:21:15' },
      { id: 2, step: 'preprocess', status: 'completed', progress: 100, completed_at: '16:22:08' },
      { id: 3, step: 'pca', status: 'completed', progress: 100, completed_at: '16:22:50' },
      { id: 4, step: 'umap', status: 'completed', progress: 100, completed_at: '16:24:18' },
      { id: 5, step: 'cluster', status: 'completed', progress: 100, completed_at: '16:25:01' },
      { id: 6, step: 'de', status: 'completed', progress: 100, completed_at: '16:26:30' },
      { id: 7, step: 'biomarkers', status: 'completed', progress: 100, completed_at: '16:27:18' },
    ],
    benchmarks: {
      hybrid: {
        method: 'Hybrid PCA → UMAP (CellMap)',
        knn_preservation: 0.887,
        trustworthiness: 0.945,
        continuity: 0.963,
        runtime_seconds: 4.45,
        visualization_latency_ms: 4450,
        global_distance_correlation: 0.755,
        dual_objective_score: 0.931,
      },
      direct: {
        method: 'Direct UMAP (Raw HVG)',
        knn_preservation: 0.689,
        trustworthiness: 0.861,
        continuity: 0.808,
        runtime_seconds: 13.6,
        visualization_latency_ms: 13600,
        global_distance_correlation: 0.375,
        dual_objective_score: 0.762,
      },
      pca: {
        method: 'Principal Component Analysis (PC1 vs PC2)',
        knn_preservation: 0.621,
        trustworthiness: 0.917,
        continuity: 0.895,
        runtime_seconds: 0.61,
        visualization_latency_ms: 610,
        global_distance_correlation: 0.825,
        dual_objective_score: 0.862,
      },
    },
    qc: {
      cells_before: 4150,
      cells_after: 3820,
      genes_before: 2240,
      genes_after: 2180,
      median_counts: 5210,
      median_genes: 1450,
      median_mito_pct: 3.85,
      doublet_rate_pct: 4.1,
      low_quality_dropped: 220,
      apoptotic_dropped: 110,
    },
    clusters: [
      {
        id: 0,
        name: 'Hyper-inflammatory Macrophages',
        cell_count: 1450,
        percentage: 38.0,
        dominant_markers: ['IL6', 'TNF', 'CCL2', 'CXCL10', 'STAT1'],
        batch_entropy: 0.94,
        cell_type: 'Pro-inflammatory Myeloid',
        color: '#f43f5e',
      },
      {
        id: 1,
        name: 'Exhausted CD8+ T Lymphocytes',
        cell_count: 980,
        percentage: 25.7,
        dominant_markers: ['CD8A', 'LAG3', 'PDCD1', 'HAVCR2', 'GZMB'],
        batch_entropy: 0.92,
        cell_type: 'T Lymphocyte',
        color: '#818cf8',
      },
      {
        id: 2,
        name: 'Airway Ciliated Epithelium',
        cell_count: 650,
        percentage: 17.0,
        dominant_markers: ['FOXJ1', 'TPPP3', 'ACE2', 'TMPRSS2'],
        batch_entropy: 0.88,
        cell_type: 'Respiratory Epithelium',
        color: '#06b6d4',
      },
      {
        id: 3,
        name: 'Activated Neutrophils',
        cell_count: 510,
        percentage: 13.4,
        dominant_markers: ['S100A8', 'S100A9', 'MMP9', 'CXCL8'],
        batch_entropy: 0.87,
        cell_type: 'Granulocyte',
        color: '#f59e0b',
      },
      {
        id: 4,
        name: 'Plasmacytoid Dendritic Cells (pDC)',
        cell_count: 230,
        percentage: 6.0,
        dominant_markers: ['LILRA4', 'IL3RA', 'IRF7', 'TLR7'],
        batch_entropy: 0.83,
        cell_type: 'Antigen-Presenting Cell',
        color: '#a855f7',
      },
    ],
    biomarkers: [
      {
        id: 401,
        gene_symbol: 'IL6',
        cluster_id: 0,
        cluster_name: 'Hyper-inflammatory Macrophages',
        rank: 1,
        composite_score: 0.982,
        log2_fc: 5.12,
        p_value_adj: 3.4e-65,
        roc_auc: 0.996,
        specificity: 0.989,
        prevalence: 0.965,
        prioritization_category: 'Tier 1',
        validation_status: 'Clinically Validated',
        fraction_in_cluster: 0.97,
        fraction_out_cluster: 0.02,
        pathways: ['Cytokine Storm Syndrome', 'JAK-STAT Signaling', 'IL-6 / STAT3 Hallmark'],
        druggability: {
          target_class: 'Pro-inflammatory Interleukin',
          approved_drugs: ['Tocilizumab (Anti-IL6R FDA approved)', 'Sarilumab'],
          clinical_phase: 'FDA Approved for COVID ARDS',
          dgidb_category: 'Druggable Genome Tier 1',
        },
      },
      {
        id: 402,
        gene_symbol: 'CXCL10',
        cluster_id: 0,
        cluster_name: 'Hyper-inflammatory Macrophages',
        rank: 2,
        composite_score: 0.968,
        log2_fc: 4.65,
        p_value_adj: 1.8e-58,
        roc_auc: 0.991,
        specificity: 0.978,
        prevalence: 0.942,
        prioritization_category: 'Tier 1',
        validation_status: 'Clinically Validated',
        fraction_in_cluster: 0.95,
        fraction_out_cluster: 0.03,
        pathways: ['Chemokine Signaling Pathway', 'T-Cell Chemoattraction'],
        druggability: {
          target_class: 'CXCR3 Ligand Chemokine',
          approved_drugs: ['Eldelumab (Phase II Clinical Trial)'],
          clinical_phase: 'Phase II Clinical Trial',
          dgidb_category: 'Druggable Genome Tier 2',
        },
      },
    ],
    dotplot: [
      {
        gene_symbol: 'IL6',
        clusters: [
          { cluster_id: 0, cluster_name: 'Macrophages', fraction_expressed: 0.97, mean_expression: 5.0 },
          { cluster_id: 1, cluster_name: 'CD8+ T', fraction_expressed: 0.02, mean_expression: 0.08 },
          { cluster_id: 2, cluster_name: 'Epithelium', fraction_expressed: 0.12, mean_expression: 0.6 },
          { cluster_id: 3, cluster_name: 'Neutrophils', fraction_expressed: 0.25, mean_expression: 1.2 },
          { cluster_id: 4, cluster_name: 'pDC', fraction_expressed: 0.03, mean_expression: 0.1 },
        ],
      },
      {
        gene_symbol: 'CXCL10',
        clusters: [
          { cluster_id: 0, cluster_name: 'Macrophages', fraction_expressed: 0.95, mean_expression: 4.8 },
          { cluster_id: 1, cluster_name: 'CD8+ T', fraction_expressed: 0.05, mean_expression: 0.2 },
          { cluster_id: 2, cluster_name: 'Epithelium', fraction_expressed: 0.22, mean_expression: 1.1 },
          { cluster_id: 3, cluster_name: 'Neutrophils', fraction_expressed: 0.18, mean_expression: 0.9 },
          { cluster_id: 4, cluster_name: 'pDC', fraction_expressed: 0.08, mean_expression: 0.4 },
        ],
      },
      {
        gene_symbol: 'ACE2',
        clusters: [
          { cluster_id: 0, cluster_name: 'Macrophages', fraction_expressed: 0.01, mean_expression: 0.05 },
          { cluster_id: 1, cluster_name: 'CD8+ T', fraction_expressed: 0.01, mean_expression: 0.03 },
          { cluster_id: 2, cluster_name: 'Epithelium', fraction_expressed: 0.88, mean_expression: 4.6 },
          { cluster_id: 3, cluster_name: 'Neutrophils', fraction_expressed: 0.01, mean_expression: 0.02 },
          { cluster_id: 4, cluster_name: 'pDC', fraction_expressed: 0.02, mean_expression: 0.08 },
        ],
      },
    ],
    pathways: [
      {
        pathway_id: 'H_CYTOKINE_STORM',
        pathway_name: 'Hyper-inflammatory Cytokine Storm Response',
        source: 'MSigDB Hallmark',
        p_value: 4.5e-25,
        p_value_adj: 9.0e-23,
        overlap_genes: ['IL6', 'TNF', 'CCL2', 'CXCL10', 'IL1B', 'IFNG', 'STAT1'],
        cluster_id: 0,
        cluster_name: 'Hyper-inflammatory Macrophages',
      },
    ],
    embeddings: {
      hybrid: [
        ...generateClusterPoints(130, 0, 'Macrophages', -5.8, -4.2, 1.8, 1.6, 6101),
        ...generateClusterPoints(100, 1, 'CD8+ T', -2.1, 6.5, 1.6, 1.4, 6202),
        ...generateClusterPoints(70, 2, 'Epithelium', 6.2, 3.8, 1.4, 1.3, 6303),
        ...generateClusterPoints(50, 3, 'Neutrophils', 4.8, -5.2, 1.5, 1.3, 6404),
        ...generateClusterPoints(30, 4, 'pDC', -7.5, 2.8, 1.1, 1.1, 6505),
      ],
      direct: [
        ...generateClusterPoints(130, 0, 'Macrophages', 6.5, -5.1, 2.7, 2.5, 6606),
        ...generateClusterPoints(100, 1, 'CD8+ T', -6.1, 4.2, 2.9, 2.4, 6707),
        ...generateClusterPoints(70, 2, 'Epithelium', 2.5, 8.5, 2.6, 2.8, 6808),
        ...generateClusterPoints(50, 3, 'Neutrophils', -4.2, -7.1, 2.8, 2.4, 6909),
        ...generateClusterPoints(30, 4, 'pDC', 0.2, 0.5, 3.4, 3.1, 7010),
      ],
      pca: [
        ...generateClusterPoints(130, 0, 'Macrophages', -12.8, -9.5, 5.8, 5.2, 7111),
        ...generateClusterPoints(100, 1, 'CD8+ T', -6.2, 12.8, 5.4, 4.8, 7212),
        ...generateClusterPoints(70, 2, 'Epithelium', 13.5, 6.2, 5.9, 5.1, 7313),
        ...generateClusterPoints(50, 3, 'Neutrophils', 9.1, -11.4, 4.9, 4.5, 7414),
        ...generateClusterPoints(30, 4, 'pDC', -15.1, 4.5, 4.1, 3.8, 7515),
      ],
    },
  },
};

export interface VolcanoGeneItem {
  gene: string;
  log2fc: number;
  pvalue_adj: number;
  cluster: number;
  is_marker?: boolean;
}

export const VOLCANO_GENES: VolcanoGeneItem[] = [
  { gene: 'CD3D', log2fc: 3.45, pvalue_adj: 1.2e-45, cluster: 0, is_marker: true },
  { gene: 'CD3E', log2fc: 3.21, pvalue_adj: 4.5e-42, cluster: 0, is_marker: true },
  { gene: 'CD4', log2fc: 2.85, pvalue_adj: 3.2e-36, cluster: 0, is_marker: true },
  { gene: 'IL7R', log2fc: 2.45, pvalue_adj: 8.7e-30, cluster: 0, is_marker: true },
  { gene: 'LEF1', log2fc: 2.12, pvalue_adj: 1.5e-24, cluster: 0, is_marker: true },
  { gene: 'MS4A1', log2fc: 4.12, pvalue_adj: 3.1e-52, cluster: 1, is_marker: true },
  { gene: 'CD19', log2fc: 3.89, pvalue_adj: 8.7e-49, cluster: 1, is_marker: true },
  { gene: 'CD79A', log2fc: 3.52, pvalue_adj: 2.4e-41, cluster: 1, is_marker: true },
  { gene: 'CD79B', log2fc: 3.15, pvalue_adj: 9.1e-35, cluster: 1, is_marker: true },
  { gene: 'PAX5', log2fc: 2.78, pvalue_adj: 4.2e-28, cluster: 1, is_marker: true },
  { gene: 'CD14', log2fc: 3.67, pvalue_adj: 5.2e-44, cluster: 2, is_marker: true },
  { gene: 'LYZ', log2fc: 3.42, pvalue_adj: 1.1e-39, cluster: 2, is_marker: true },
  { gene: 'S100A8', log2fc: 2.76, pvalue_adj: 8.9e-31, cluster: 2, is_marker: true },
  { gene: 'S100A9', log2fc: 2.65, pvalue_adj: 4.5e-29, cluster: 2, is_marker: true },
  { gene: 'VCAN', log2fc: 2.34, pvalue_adj: 1.8e-22, cluster: 2, is_marker: true },
  { gene: 'NKG7', log2fc: 4.02, pvalue_adj: 2.4e-48, cluster: 3, is_marker: true },
  { gene: 'GNLY', log2fc: 3.78, pvalue_adj: 6.8e-46, cluster: 3, is_marker: true },
  { gene: 'KLRD1', log2fc: 3.15, pvalue_adj: 5.6e-38, cluster: 3, is_marker: true },
  { gene: 'PRF1', log2fc: 2.92, pvalue_adj: 3.1e-33, cluster: 3, is_marker: true },
  { gene: 'FCER1A', log2fc: 4.25, pvalue_adj: 1.5e-50, cluster: 4, is_marker: true },
  { gene: 'CLEC10A', log2fc: 3.55, pvalue_adj: 7.9e-41, cluster: 4, is_marker: true },
  { gene: 'CD1C', log2fc: 3.12, pvalue_adj: 2.8e-32, cluster: 4, is_marker: true },
  { gene: 'HLA-DRA', log2fc: 2.98, pvalue_adj: 1.1e-29, cluster: 4, is_marker: true },
  { gene: 'GAPDH', log2fc: 0.12, pvalue_adj: 0.45, cluster: 0, is_marker: false },
  { gene: 'ACTB', log2fc: -0.08, pvalue_adj: 0.72, cluster: 0, is_marker: false },
  { gene: 'B2M', log2fc: 0.42, pvalue_adj: 0.08, cluster: 1, is_marker: false },
  { gene: 'RPL13A', log2fc: -0.25, pvalue_adj: 0.22, cluster: 2, is_marker: false },
  { gene: 'RPS18', log2fc: 0.15, pvalue_adj: 0.61, cluster: 3, is_marker: false },
  { gene: 'EEF1A1', log2fc: -0.18, pvalue_adj: 0.35, cluster: 4, is_marker: false },
  { gene: 'MKI67', log2fc: -2.15, pvalue_adj: 1.4e-18, cluster: 0, is_marker: false },
  { gene: 'TOP2A', log2fc: -1.95, pvalue_adj: 5.6e-15, cluster: 1, is_marker: false },
  { gene: 'PCNA', log2fc: -1.82, pvalue_adj: 8.2e-14, cluster: 2, is_marker: false },
];

export const LAMBDA_SWEEP_DATA = [
  { lambda: 0.0, hybrid: 0.884, direct: 0.695, pca: 0.612 },
  { lambda: 0.1, hybrid: 0.888, direct: 0.702, pca: 0.633 },
  { lambda: 0.2, hybrid: 0.895, direct: 0.711, pca: 0.654 },
  { lambda: 0.3, hybrid: 0.906, direct: 0.724, pca: 0.685 },
  { lambda: 0.4, hybrid: 0.918, direct: 0.742, pca: 0.730 },
  { lambda: 0.5, hybrid: 0.927, direct: 0.769, pca: 0.858 },
  { lambda: 0.6, hybrid: 0.932, direct: 0.758, pca: 0.871 },
  { lambda: 0.7, hybrid: 0.936, direct: 0.742, pca: 0.885 },
  { lambda: 0.8, hybrid: 0.939, direct: 0.720, pca: 0.898 },
  { lambda: 0.9, hybrid: 0.941, direct: 0.690, pca: 0.908 },
  { lambda: 1.0, hybrid: 0.942, direct: 0.650, pca: 0.915 },
];

export const FEATURE_COMPARISON = {
  selection: {
    method: 'Highly Variable Gene (HVG) Selection',
    input_dims: 20000,
    output_dims: 2000,
    preserves: 'Preserves original biological gene identities and interpretable biomarkers.',
    technique: 'Seurat v3 / scanpy.pp.highly_variable_genes (dispersion ranking)',
  },
  extraction: {
    method: 'Principal Component Analysis (PCA)',
    input_dims: 2000,
    output_dims: 50,
    preserves: 'Compresses orthogonal global variance onto top linear eigenspace directions.',
    technique: 'ARPACK Truncated SVD / scanpy.tl.pca (eigen-decomposition)',
  },
};


